version: '3.8'

services:
  frontend:
    build: ./Deeployin-ui
    ports:
      - "80:80"
    environment:
      - VITE_API_BACKEND1=http://localhost:5001
      - VITE_API_BACKEND2=http://localhost:5002
    restart: always

  backend1:
    build: ./Dockerfile-Generator
    ports:
      - "5001:5000"
    environment:
      - OPENAI_API_KEY=
      - SECRET_KEY=
      - DEPLOY_PATH=
    depends_on:
      - db
    restart: always

  backend2:
    build: ./Docker-Deploy-Automation
    ports:
      - "5002:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=docker
      - DB_USER=root
      - DB_PASS=password
      - SECRET_KEY=
      - DEPLOY_PATH=
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    restart: always
